name:                two-danode-fluid
version:             0.1.0.0
github:              "fabricatedmath/two-danode-fluid"
license:             BSD3
author:              "Charles Durham"
maintainer:          "fabricatedmath@gmail.com"
copyright:           "2018 Charles Durham"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/fabricatedmath/two-danode-fluid#readme>

dependencies:
- base >= 4.7 && < 5
- hint
- lens
- repa
- vector
- linear
- accelerate
- accelerate-io
- accelerate-llvm-ptx
- colour-accelerate
- linear-accelerate
- two-danode

library:
  source-dirs: src

executables:
  two-danode-fluid-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - two-danode-fluid
    - pipes
    - pipes-safe
    - pipes-graphics-accelerate
    - pipes-graphics-repa
    - bytestring
    - aeson

tests:
  two-danode-fluid-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - two-danode-fluid
